name: Build Docker Image

on:
  workflow_dispatch:
  push:
    branches: 
     - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Init buildx
      run: docker buildx create --use
      
    - name: Quay login
      run: docker login -u="$QUAY_USERNAME" -p="$QUAY_TOKEN" quay.io
      env:
        QUAY_TOKEN: ${{ secrets.quay_token }}
        QUAY_USERNAME: ${{ secrets.quay_username }}
    
    - name: Build docker image
      run: docker buildx build --platform linux/amd64 ./ --tag quay.io/lunarway/swaggerswift:latest --push
